name: Build Proton
on:
    push:
        branches: [ "new" ]
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Workaround for disk space
                run: |  # https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
                    sudo rm -rf /usr/share/dotnet
                    sudo rm -rf /opt/ghc
                    sudo rm -rf "/usr/local/share/boost"
                    sudo rm -rf "$AGENT_TOOLSDIRECTORY"
            -   name: Build
                run: |
                    bash script
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

